@WebAPI_HostAddress = https://localhost:7263

GET {{WebAPI_HostAddress}}/api/products
Accept: application/json

###

GET {{WebAPI_HostAddress}}/api/products/b99d91fc-274b-407b-a5d0-b8b7288df96f
Accept: application/json

###

POST {{WebAPI_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "{{$random.commerce.productName}}",
  "description": "{{$random.commerce.productName}}",
  "value": 10,
  "supplier_id": "2f99e135-a685-45c4-a6ed-529b2e3d4a27"
}